### ISSUE TITLE
Android call to checkScanPermission crashes app when ACCESS_FINE_LOCATION has not been called yet

### ISSUE THREAD

**Issue by jdegger** [X-Guard/react-native-flic2#10]
```
java.lang.SecurityException: ACCESS_FINE_LOCATION not granted. Please call `Activity.requestPermissions(String[], int)` first.
    at io.flic.flic2libandroid.Flic2Manager.checkScanPermission(Flic2Manager.java:486)
    at io.flic.flic2libandroid.Flic2Manager.startScan(Flic2Manager.java:506)
    at nl.xguard.flic2.Flic2.startScan(Flic2.java:239)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
    at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
    at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
    at android.os.Handler.handleCallback(Handler.java:873)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
    at android.os.Looper.loop(Looper.java:214)
    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
    at java.lang.Thread.run(Thread.java:764)
```

**Comment by jdegger** [comment]
The app should not crash when fine location is not given but gracefully stop instead with maybe a logged warning.
